version: "3.8"

services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  bug-tracker-service:
    image: bug-tracker-service
    environment:
      - ENVIRONMENT=PRODUCTION
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  postgres: ~
  bug-tracker-service: ~
