version: "3.8"

services:
  postgres:
    platform: linux/amd64
    image: postgres:14.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always
  bug-tracker-service:
    platform: linux/amd64
    build: .
    environment:
      - ENVIRONMENT=PRODUCTION
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    links:
      - postgres
    restart: always

volumes:
  postgres: ~
  bug-tracker-service: ~
