version: "3.8"

services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - ENABLE_OVERCOMMIT_MEMORY=true
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    ports:
      - '6379:6379'
    volumes:
      - './volumes/redis:/bitnami/redis/data'
    restart: always

  bug-tracker-service:
    platform: linux/amd64
    build: .
    environment:
      - ENVIRONMENT=PRODUCTION
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
    restart: always

volumes:
  postgres: ~
  bug-tracker-service: ~
  redis: ~
