version: "3.8"

services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../../volumes/postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres: ~
