import os

import psycopg2

from dotenv import load_dotenv

load_dotenv()


def get_postgres_connection():
    host = os.environ.get('POSTGRES_HOST')
    database = os.environ.get('POSTGRES_DATABASE')
    user = os.environ.get('POSTGRES_USER')
    password = os.environ.get('POSTGRES_PASSWORD')

    connection = psycopg2.connect(
        host=host,
        database=database,
        user=user,
        password=password
    )

    return connection


def main():
    create_table_query = '''
        CREATE TABLE IF NOT EXISTS users (
            internal_user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            external_user_id TEXT NOT NULL,
            username TEXT NOT NULL,
            email TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
        );
    '''

    with get_postgres_connection() as connection, connection.cursor() as cursor:
        try:
            cursor.execute(create_table_query)
            connection.commit()
        except Exception as error:
            print(error)
            connection.rollback()


if __name__ == "__main__":
    main()
