from utility import get_postgres_connection


def main():
    TABLE_NAME: str = 'projects'

    with get_postgres_connection() as connection, connection.cursor() as cursor:
        create_table_query: str = f'''
            CREATE TABLE IF NOT EXISTS {TABLE_NAME} (
                project_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                user_id INT NOT NULL REFERENCES users(internal_user_id),
                administrator_id INT NOT NULL REFERENCES users(internal_user_id),
                co_administrator_ids INT[] NOT NULL,
                member_ids INT[] NOT NULL,
                name text NOT NULL,
                description text NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', NOW())
            );
        '''

        try:
            cursor.execute(create_table_query)
            connection.commit()
        except Exception as error:
            print(error)
            connection.rollback()


if __name__ == '__main__':
    main()
