version: '3.8'

services:
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - ENABLE_OVERCOMMIT_MEMORY=true
      # - REDIS_PASSWORD=redis
      # - REDIS_PORT=6379
    ports:
      - '6379:6379'
    volumes:
      - '../../volumes/redis:/bitnami/redis/data'
    restart: always

volumes:
  redis_data: ~
